name: deploy-website

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'Dockerfile'
  workflow_run:
    workflows: ["build-image"]
    types:
      - completed
    branches: ["main"]

env:
  NAME: "Aragorn_Dai"

jobs:
  build-website:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Build Website
        run: npm run build
      - name: Generate Resume PDF
        working-directory: src/latex
        run: |
          xelatex -interaction=nonstopmode -halt-on-error resume.tex
      - name: Copy Resume PDF
        run: |
          cp src/latex/resume.pdf "dist/${{ env.NAME }}_Resume.pdf"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: build-website
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
